Algoritmo "apresente soma de a e b mais 45% do numero"

Var
// Seção de Declarações das variáveis 
     a, b: inteiro
     m: real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
       escreval("digite dois numero: ")
       leia(a, b)
       
       m <- (a + b)*0.45
       escreval("isto é a soma mais 45%  de ",a," e ",b," é igual a ",m,".")


Fimalgoritmo